# Generated by Django 4.1.7 on 2023-03-10 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_group', models.CharField(max_length=250)),
                ('date_of_start', models.DateField(default=datetime.datetime.today, verbose_name='Beginning')),
                ('description', models.TextField()),
            ],
        ),
    ]
