# Generated by Django 4.1.7 on 2023-03-13 11:03

from django.db import migrations, models
import student.validators


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, validators=[student.validators.valid_email_domains]),
        ),
    ]
