# Generated by Django 4.1.7 on 2023-03-13 11:54

from django.db import migrations, models
import student.validators


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, validators=[student.validators.ValidEmailDomain('@gmail.com', '@yahoo.com')]),
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
